### PR TITLE
Update lsl-sys to use liblsl v1.16.2

### PR DESCRIPTION
**Pull request by tufteddeer**
This PR updates the lsl-sys crate to use the latest tagged release of liblsl.

- updated liblsl submodule
- fixed linking in build.rs
- regenerated bindings

I tried out the included examples and while I'm not experienced enough with LSL to spot potential subtle quirks, all of them compiled and did their things. I also used this version as dependency for another crate to send data to the LabRecorder, which also worked fine.

### CODE REVIEW

**Comment by cboulay** [comment]
This looks good to me but I'm not setup to test this. @chkothe are you?

**Comment by chkothe** [comment]
Yeah, should be able to check & merge. Thanks @tufteddeer! Will get to it after the Thanksgiving break.

**Comment by tufteddeer** [comment]
Hi @chkothe, any updates on this one? :)

**Comment by chkothe** [comment]
Hey @tufteddeer -- so sorry, it's been super busy over here! I'll be working on this today though & should be ready in a couple hours.

**Comment by chkothe** [comment]
Confirmed to work. Thanks!

**Pull request merged**
